const Data5 = [ {
    id: 1,
    img5: "https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=600",
    name: "Juice",
    link: "secret",
    size: "Large",
}, {
    id: 2,
    img5: "https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?auto=compress&cs=tinysrgb&w=600",
    name: "Juice",
    link: "secret",
    size: "Small",
}, {
    id: 3,
    img5: "https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=600",
    name: "Juice",
    link: "secret",
    size: "Medium",
},  {
    id: 4,
    img5: "https://images.pexels.com/photos/2581922/pexels-photo-2581922.jpeg?auto=compress&cs=tinysrgb&w=600",
    name: "Juice",
    link: "secret",
    size: "Medium",
}, {
    id: 5,
    img5: "https://images.pexels.com/photos/1974596/pexels-photo-1974596.jpeg?auto=compress&cs=tinysrgb&w=600",
    name: "Juice",
    link: "secret",
    size: "Medium",
},  {
    id: 6,
    img5: "https://images.pexels.com/photos/221540/pexels-photo-221540.jpeg?auto=compress&cs=tinysrgb&w=600",
    name: "Juice",
    link: "secret",
    size: "Medium",
}, 
{
    id: 7,
    img5: "https://images.pexels.com/photos/259962/pexels-photo-259962.jpeg?auto=compress&cs=tinysrgb&w=600",
    name: "Juice",
    link: "secret",
    size: "Medium",
},  {
    id: 8,
    img5: "https://images.pexels.com/photos/208736/pexels-photo-208736.jpeg?auto=compress&cs=tinysrgb&w=600",
    name: "Juice",
    link: "secret",
    size: "Medium",
}, 
{
    id: 9,
    img5: "https://images.pexels.com/photos/1370704/pexels-photo-1370704.jpeg?auto=compress&cs=tinysrgb&w=600",
    name: "Juice",
    link: "secret",
    size: "Medium",
},  {
    id: 10,
    img5: "https://images.pexels.com/photos/262405/pexels-photo-262405.jpeg?auto=compress&cs=tinysrgb&w=600",
    name: "Juice",
    link: "secret",
    size: "Medium",
}, 
{
    id: 11,
    img5: "https://images.pexels.com/photos/210617/pexels-photo-210617.jpeg?auto=compress&cs=tinysrgb&w=600",
    name: "Juice",
    link: "secret",
    size: "Medium",
},  {
    id: 12,
    img5: "https://images.pexels.com/photos/2253916/pexels-photo-2253916.jpeg?auto=compress&cs=tinysrgb&w=600",
    name: "Juice",
    link: "secret",
    size: "Medium",
}, 
 {
    id: 13,
    img5: "https://images.pexels.com/photos/2253916/pexels-photo-2253916.jpeg?auto=compress&cs=tinysrgb&w=600",
    name: "Juice",
    link: "secret",
    size: "Medium",
}, 
{
    id: 14,
    img5: "https://images.pexels.com/photos/1438834/pexels-photo-1438834.jpeg?auto=compress&cs=tinysrgb&w=600",
    name: "Juice",
    link: "secret",
    size: "Medium",
},  {
    id: 15,
    img5: "https://images.pexels.com/photos/2351649/pexels-photo-2351649.jpeg?auto=compress&cs=tinysrgb&w=600",
    name: "Juice",
    link: "secret",
    size: "Medium",
}, 

]

export default Data5;